### ISSUE TITLE
Does Destroy command prompt first?

### ISSUE THREAD

**Issue by jacobgraf** [m1keil/alfred-vagrant-workflow#12]
First off, thanks so much for creating this workflow. It really comes in handy!

My question is related to destroying Vagrant boxes. If you select Destroy, does it prompt you or anything? The reason I ask is that it's so close to halt, I would hate to accidentally click destroy and have it immediately destroy my box. Usually this isn't an issue, but I am using Homestead and have a lot of databases running in the box that would be gone if I accidentally hit destroy.

If there currently is no prompt, would that be something worth adding?

If not, can I disable the 'destroy' option all together? For me, if I needed to destroy the box, I would be happy to manually do it from the command line.

Thanks for listening!

**Comment by m1keil** [comment]
Hey,
thanks for the feedback. 
I never thought about it myself, but I see your point. I will add this option in next release.
For now, if you want to disable this option manually you can do the following:
1. Open workflow directory
2. Open for edit `common.py`
3. Remove the `destroy` element from `actions` dictionary. Final result should be like this:

```
actions = {
    'up': {
        'desc': 'Starts and provisions the vagrant environment',
        'flags': None,
        'state': ['paused', 'stopped'],
        'dir_action': True,
    },
    'halt': {
        'desc': 'Stops the machine',
        'flags': None,
        'state': ['running', 'paused'],
        'dir_action': True,
    },
    'resume': {
        'desc': 'Resume a suspended machine',
        'flags': None,
        'state': ['paused'],
        'dir_action': True,
    },
    'suspend': {
        'desc': 'Suspends the machine',
        'flags': None,
        'state': ['running'],
        'dir_action': True,
    },
    'provision': {
        'desc': 'Provisions the machine',
        'flags': None,
        'state': ['running'],
        'dir_action': True,
    },
    'rdp': {
        'desc': 'Connects to machine via RDP',
        'flags': None,
        'state': ['running'],
        'dir_action': False,
    },
    'ssh': {
        'desc': 'Connects to machine via SSH',
        'flags': None,
        'state': ['running'],
        'dir_action': False,
    }
}
```
4. Save and check workflow doesn't contain the destroy option anymore.

**Comment by jacobgraf** [comment]
Thanks so much for your detailed response! I'll kee an eye out for future updates! :-)
