### ISSUE TITLE
ssh doesn't work

### ISSUE THREAD

**Issue by hassankhan** [m1keil/alfred-vagrant-workflow#13]
When I shift-enter on my Vagrant machine, it doesn't do anything.

**Comment by m1keil** [comment]
Hey,
that's weird. Basically the way it works is sending a command to Alfred2 to open its default terminal and run `vagrant ssh ..` in it. 
Is your default terminal in Alfred2 is terminal.app or iTerm2 (or maybe custom one?)

**Comment by m1keil** [comment]
I just checked it myself, and you are right, looks like ssh action is broken when using alfred2 and iterm2. I'm trying to figure out if this is an alfred2 bug or iterm2 bug.

**Comment by m1keil** [comment]
From further inspection it looks like it's a bug when iTerm2 is nightly version. I managed to successfully run the action when using stable iTerm2 2.0 and beta 2.1. However on nightly version it didn't work. Can you share your default terminal with Alfred and if that's iTerm2 or any custom terminal, what version do you use?

**Comment by hassankhan** [comment]
Hi, thanks for the reply, on my work machine (iMac retina 27", OSX 10.10) it `cd`s to the right folder but doesn't ssh. On my laptop (MBP 13", late 2010, OSX 10.9) it doesn't do anything at all. 

Alfred is configured on both machines to use iTerm as its default terminal.

**Comment by m1keil** [comment]
What's the version of your iTerm?

**Comment by hassankhan** [comment]
Running iTerm v2.1 and the latest Alfred (v2.7.1)

**Comment by m1keil** [comment]
that's....weird.

If you could confirm the exact iTerm versions it would greatly help. 
You can find iTerm version information in the iTerm menu -> `About iTerm`.

Please write exact version. For example my version is `Build 1.0.0.20140714-nightly`.

Also, on the machine where `cd` works but `ssh` doesn't, do you see any error message appearing on the terminal after you choose `ssh` action? Or the terminal never opens?

**Comment by hassankhan** [comment]
I'm at work right now, so the work machine is running iTerm v2.1:

![screen shot 2015-04-30 at 12 22 13](https://cloud.githubusercontent.com/assets/1781985/7411819/94b48762-ef33-11e4-99e7-3d3ed5cfcc69.png)

On my laptop, it doesn't display anything or do anything. On the work machine, it shows the following in the terminal:

```
/Users/User/Desktop/Projects/firestead/Vagrantfile:17:in `read': No such file or directory - /Users/User/firestead/config.yaml (Errno::ENOENT)
	from /Users/User/Desktop/Projects/firestead/Vagrantfile:17:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:138:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/ssh/command.rb:41:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

**Comment by m1keil** [comment]
@hassankhan thank you very much for the details.
I'm going to investigate further.

Regarding the second issue (with the error log) - this usually happens because something is wrong in your `Vagrantfile`. Since my workflow use `vagrant ssh <machine id>` to ssh into the machine, Vagrant will process Vagrantfile. 
In your case it looks like Vagrantfile have some issues, specifically a missing path -> `/Users/User/firestead/config.yaml`.

I think you'll get the same issue if you try to open your terminal and do `vagrant ssh <machine id>` by yourself. Could you please confirm?

**Comment by hassankhan** [comment]
Hi, that's the weird part, if I manually `cd` to the folder and `vagrant ssh`, it all works fine.

**Comment by m1keil** [comment]
Hmm, might be because the current working directory is different?

Can you please check the following:
1. Open shell in any directory that is NOT the same as your Vagrantfile's directory
2. Run `vagrant global status`
3. Copy the suitable id for the suitable environment you trying to ssh (the left most column in the table)
4. Run `vagrant ssh <id>` where <id> is the `id` you just copied

Can you tell me if that gives you the same error?

**Comment by hassankhan** [comment]
Hi, I get the following error:

```
/Users/User/Desktop/Projects/firestead/Vagrantfile:17:in `read': No such file or directory - /Users/User/firestead/config.yaml (Errno::ENOENT)
	from /Users/User/Desktop/Projects/firestead/Vagrantfile:17:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:138:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/ssh/command.rb:41:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

Looks the same to me :confused:

**Comment by m1keil** [comment]
Great, that's actually good result because it means I can probably fix it :-)

**Comment by m1keil** [comment]
I'm going to investigate further regarding first issue.
Regarding the second one, I'll try to fix it in the next release.

**Comment by hassankhan** [comment]
Awesome, thanks for being so quick with replying :smile: and for all your help

**Comment by m1keil** [comment]
Hopefully this isn't an issue in 2.x

**Comment by hassankhan** [comment]
Aww, unfortunately I've moved onto using Docker now :(
