### ISSUE TITLE
action failure on vagrant 1.7.4

### ISSUE THREAD

**Issue by mcapanema** [m1keil/alfred-vagrant-workflow#15]
I have upgraded vagrant to last version available(1.7.4), then the workflow stopped to work.
Whenever a run and `:vagrant-id <action>` it raise and erro such as `<action> failed`:
![vagrant-error](https://cloud.githubusercontent.com/assets/1120467/9912953/8d4f13a6-5c80-11e5-9bbd-7c0ba7e128f1.jpg)
Also, I tried to enable Alfred debugger to see what happens, but, it shows no error.
The funny thing is that when I run `:vagrant-id ssh` it just works.

**Comment by m1keil** [comment]
Hey,
I think good way of debugging this would be to check the log while trying to do the action. 
Open the log by writing `vagrant workflow:openlog`
And try recreating the problem.

I suspect there's a failure in finding Vagrant utility, which might be related to some changes in OS X or Alfred. If you can share the error log it would be great.

**Comment by mcapanema** [comment]
Great tip @m1keil I didn't know this command, it helped me a lot.
The problem was pretty stupid:
```
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
``` 

So I just opened up the workflow and added the PATH to the script executor, like that:
```sh
PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin'

python vagrantup.py --openenv {query}
```

**Comment by m1keil** [comment]
Awesome, thanks for the update. I'll definitely add an easier way to edit the path in the future.
