### ISSUE TITLE
VM stays in status running after removing the folder

### ISSUE THREAD

**Issue by toonjanssens** [m1keil/alfred-vagrant-workflow#16]
I have a VM with status running without a vagrant folder anymore. I can not remove it from the list or run any commando on it. Nothing happens after hitting return on the VM in the list.

I tried to create a new vagrant folder in the same location, in the hope I could run the remove command, but it didn't work. How can I remove it from list?

**Comment by m1keil** [comment]
Hey,
this is a small Vagrant inconvenience.
If you removed a folder while VM appears to be running, and you would like to clean it up, you need to do the following: 
1) Delete the vm from Virtualbox (assuming it's VBox we are talking about)
2) Run in your terminal: `vagrant global-status --prune`

Should do the trick.

**Comment by toonjanssens** [comment]
Great, that did the trick! Thank you.
Btw, great Alfred workflow!

**Comment by m1keil** [comment]
Great to hear. I think I should do a small FAQ :-)

Thanks!
