### ISSUE TITLE
No JSON object could be detected

### ISSUE THREAD

**Issue by beedaan** [m1keil/alfred-vagrant-workflow#20]
![screen shot 2016-08-31 at 7 22 07 am](https://cloud.githubusercontent.com/assets/884240/18132441/bd1a559e-6f4b-11e6-8ff5-7d11b021977d.png)

Using Alfred 3

**Comment by m1keil** [comment]
Hey @beedaan,
does this happen right after install?

Could you please share the logs with me? (run `vagrant workflow:openlogs` and copy/paste the error here)

**Comment by beedaan** [comment]
Everything was working fine for awhile, and then all of a sudden I started seeing the error.  I reinstalled the Alfred workflow and I still see the error.  I'll try to reinstall vagrant next.

I ran `vagrant workflow:openlogs` and the command wasn't recognized.  I'm fairly new to Vagrant, so I'm not exactly sure what that command does.  I can run vagrant with the [debugger on](https://www.vagrantup.com/docs/other/debugging.html), but I'm not sure how that will help debug the workflow.

**Comment by m1keil** [comment]
Hey,
sorry being unclear about it - that command is an Alfred command, not a
terminal one.

it should open a log console showing the latest log file of the workflow.

thanks!

**Comment by beedaan** [comment]
Sorry for the confusion.  I'm seeing the same error message when I run that command
![screen shot 2016-09-06 at 5 50 42 am](https://cloud.githubusercontent.com/assets/884240/18274177/0515340a-73f6-11e6-8e6c-9a0ace219422.png)

**Comment by m1keil** [comment]
well that's... interesting..
Could you please run the following in your terminal and tell me if you get back anything that is not an error?

`python -c "import json; print json.load(open('$HOME/.vagrant.d/data/machine-index/index'))"`
I'm assuming that your vagrant.d path is default to ~ (if you got no idea what I'm talking about, it probably is.

The command about tried to parse the JSON content of index file - which is the internal state of vagrant. If it fails, you should get some clear error.

Also, logs files should be in `~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.sverdlik.michael`, if you could show me the content of the latest log file would be great.

**Comment by beedaan** [comment]
I just took a look and the `index` is empty.  I'm not sure how that happened, but that's what's causing the issue.  I'm going through my boxes now and running `vagrant destroy && vagrant up --provision` to add them back to the index.
