### ISSUE TITLE
Destroyed machines still appearing in list

### ISSUE THREAD

**Issue by hugosaner** [m1keil/alfred-vagrant-workflow#21]
I destroyed a couple of machines via virtual box instead of through your Workflow. However your workflow still displays the machine. How do I reset the list to only display the machines that actually exist?

Awesome workflow! Thank you

**Comment by m1keil** [comment]
Hey @hugosaner,
the workflow will show the same status that the `vagrant status` cli will show.
In your case, I believe running `vagrant global-status --prune` from the Terminal.app should help.

If it doesn't help, try recreating the machines via `vagrant up` and destroying with `vagrant destroy`.

**Comment by hugosaner** [comment]
global-status --prune worked perfectly, thank you for the help :)

**Comment by m1keil** [comment]
Cheers!
